---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: test
spec:
 rules:
  - host: intelliqt.info
    http:
     paths:
      - path: /
        backend:
         serviceName: nginx-service
         servicePort: 80 
