---
apiVersion: v1
kind: Pod
metadata:
 name: postgres-pod
 labels:
  type: db
  author: intelliqit
spec:
 containers:
  - name: mydb
    image: postgres
    env:
     - name: POSTGRES_PASSWORD
       value: intelliqt
     - name: POSTGRES_USER
       value: myuser
     - name: POSTGRES_DB
       value: mydb
...
